#server:
#  error:
#    include-message: always
#    include-binding-errors: always
#
#spring:
#  datasource:
#    password:
#    url: jdbc:postgresql://localhost:5432/mtg_analyzer
#    username:
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgresSQLDialect
#    show-sql: true
